schema = 3

[mod]
  [mod."cloud.google.com/go/compute"]
    version = "v1.23.0"
    hash = "sha256-Pd5tMfeatH7p/Mh4b5qUqE9vMDgwwTg6/3Hb8uFZyUw="
  [mod."cloud.google.com/go/compute/metadata"]
    version = "v0.2.3"
    hash = "sha256-kYB1FTQRdTDqCqJzSU/jJYbVUGyxbkASUKbEs36FUyU="
  [mod."cloud.google.com/go/iam"]
    version = "v1.1.2"
    hash = "sha256-n4DefmHY9GGKc3xdsC+MN9y3tYu7Sgeol1X/Lsnggks="
  [mod."cloud.google.com/go/secretmanager"]
    version = "v1.11.1"
    hash = "sha256-5oEXQy/z24V6k/OinEMKWKZYuGIDEZF07fU7Z7aMjlY="
  [mod."github.com/golang/groupcache"]
    version = "v0.0.0-20210331224755-41bb18bfe9da"
    hash = "sha256-7Gs7CS9gEYZkbu5P4hqPGBpeGZWC64VDwraSKFF+VR0="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.3"
    hash = "sha256-svogITcP4orUIsJFjMtp+Uv1+fKJv2Q5Zwf2dMqnpOQ="
  [mod."github.com/google/go-cmp"]
    version = "v0.5.9"
    hash = "sha256-lQc4O00R3QSMGs9LP8Sy7A9kj0cqV5rrUdpnGeipIyg="
  [mod."github.com/google/s2a-go"]
    version = "v0.1.7"
    hash = "sha256-E+SX/3VmRI5qN7SbnRP4Tt+gQTq93pScpY9U2tTmIU0="
  [mod."github.com/googleapis/enterprise-certificate-proxy"]
    version = "v0.3.0"
    hash = "sha256-T5gfvSce6lidXgvJBjByTm0XVqME/z1GyoIZ2oZnuAY="
  [mod."github.com/googleapis/gax-go/v2"]
    version = "v2.12.0"
    hash = "sha256-ZcXS+1B11UaJHf8D15N3ZCh00fiMUncpHd+eNRffLZ4="
  [mod."go.opencensus.io"]
    version = "v0.24.0"
    hash = "sha256-4H+mGZgG2c9I1y0m8avF4qmt8LUKxxVsTqR8mKgP4yo="
  [mod."golang.org/x/crypto"]
    version = "v0.13.0"
    hash = "sha256-4ThyrEJI4i9XBwx/q/R4jR41VJBZ/TSR0+UCkjTH95A="
  [mod."golang.org/x/net"]
    version = "v0.15.0"
    hash = "sha256-k0hgSwNmZz9nN9cqqACNHdnejV50AAwzxnoyTs9liXw="
  [mod."golang.org/x/oauth2"]
    version = "v0.12.0"
    hash = "sha256-tjNUICkISajnbZ03I3nsWEPLGqb4ZBIJE7FomynLykQ="
  [mod."golang.org/x/sync"]
    version = "v0.3.0"
    hash = "sha256-bCJKLvwExhYacH2ZrWlZ38lr1d6oNenNt2m1QqDCs0o="
  [mod."golang.org/x/sys"]
    version = "v0.12.0"
    hash = "sha256-Ht/PhBJGWNBg4ksmdUu4+7hJjFypSwoUN/8DJricd+0="
  [mod."golang.org/x/text"]
    version = "v0.13.0"
    hash = "sha256-J34dbc8UNVIdRJUZP7jPt11oxuwG8VvrOOylxE7V3oA="
  [mod."google.golang.org/api"]
    version = "v0.142.0"
    hash = "sha256-VLtWup8lrKFWhxyxyeft4vuOA/yQCkNSaJyf+OCgXVc="
  [mod."google.golang.org/appengine"]
    version = "v1.6.8"
    hash = "sha256-decMa0MiWfW/Bzr8QPPzzpeya0YWGHhZAt4Cr/bD1wQ="
  [mod."google.golang.org/genproto"]
    version = "v0.0.0-20230920204549-e6e6cdab5c13"
    hash = "sha256-G8Uce4dqKNW4ozefKsbaep0i+fIWgoMEh6U+dUpYlyA="
  [mod."google.golang.org/genproto/googleapis/api"]
    version = "v0.0.0-20230920204549-e6e6cdab5c13"
    hash = "sha256-RwzbMifM6DMY7aMd5erHOhk87t6aRNF52dqCrMJPZCo="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20230920204549-e6e6cdab5c13"
    hash = "sha256-bSfeQfAT395BTmxnVAaNzw+ZX3VpBEgrfn9yn/azUX8="
  [mod."google.golang.org/grpc"]
    version = "v1.58.1"
    hash = "sha256-Oqcw5RLWngXbcDSwFuPR3HqfWGM3WndlfEgSsObNQz8="
  [mod."google.golang.org/protobuf"]
    version = "v1.31.0"
    hash = "sha256-UdIk+xRaMfdhVICvKRk1THe3R1VU+lWD8hqoW/y8jT0="
