schema = 3

[mod]
  [mod."cloud.google.com/go/compute"]
    version = "v1.12.1"
    hash = "sha256-mMsdL+6R1KuFeAFqEJv8oq/cmRc9hSluEisCpGP0GTc="
  [mod."cloud.google.com/go/compute/metadata"]
    version = "v0.2.1"
    hash = "sha256-gqjkb6y5POkTWXGQtCvgygvXqoLkESB+cykKp7Mp3jI="
  [mod."cloud.google.com/go/iam"]
    version = "v0.8.0"
    hash = "sha256-legngj53V4RLUbAzDFlzL7LYv5Ano8IW28Ia3Ar69BM="
  [mod."cloud.google.com/go/secretmanager"]
    version = "v1.10.0"
    hash = "sha256-Cy6MIR2udPkNwBAdbl/OUyc3maSciasdIumPVBAXOEU="
  [mod."github.com/golang/groupcache"]
    version = "v0.0.0-20200121045136-8c9f03a8e57e"
    hash = "sha256-0E3bzqOQk4xolVEGm0GXZ6tUpgCWF7DolyyKkdPJUm4="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.2"
    hash = "sha256-IVwooaIo46iq7euSSVWTBAdKd+2DUaJ67MtBao1DpBI="
  [mod."github.com/google/go-cmp"]
    version = "v0.5.9"
    hash = "sha256-lQc4O00R3QSMGs9LP8Sy7A9kj0cqV5rrUdpnGeipIyg="
  [mod."github.com/googleapis/enterprise-certificate-proxy"]
    version = "v0.2.0"
    hash = "sha256-5gxsS5kDLqNFBkQ4eK6GS/sNn+aFknm6jjfteO+6jl4="
  [mod."github.com/googleapis/gax-go/v2"]
    version = "v2.7.0"
    hash = "sha256-n/9o8RFFDwowqSTLUPvsTE1lp4KUJpq53j733nLYrWk="
  [mod."go.opencensus.io"]
    version = "v0.24.0"
    hash = "sha256-4H+mGZgG2c9I1y0m8avF4qmt8LUKxxVsTqR8mKgP4yo="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20221014081412-f15817d10f9b"
    hash = "sha256-36IhDZR0/Zn4wT+LrXZF0aZzps0TQxShlXv5KGRf7oE="
  [mod."golang.org/x/oauth2"]
    version = "v0.0.0-20221014153046-6fdb5e3db783"
    hash = "sha256-IoygidVNqyAZmN+3macDeIefK8hhJToygpcqlwehdYQ="
  [mod."golang.org/x/sys"]
    version = "v0.0.0-20220728004956-3c1f35247d10"
    hash = "sha256-obSKM1aiGEyYNauzaL0msReglT2XL726gL89ywjFLE8="
  [mod."golang.org/x/text"]
    version = "v0.4.0"
    hash = "sha256-JvyMygdmTvWg7xhbnUB9MMk6WcYXJt8DAj4DYl82Pys="
  [mod."google.golang.org/api"]
    version = "v0.103.0"
    hash = "sha256-iUtsDmOZVYroU2pU7z867oDNz70g2yJdo6BRJ1nu55Q="
  [mod."google.golang.org/appengine"]
    version = "v1.6.7"
    hash = "sha256-zIxGRHiq4QBvRqkrhMGMGCaVL4iM4TtlYpAi/hrivS4="
  [mod."google.golang.org/genproto"]
    version = "v0.0.0-20221201164419-0e50fba7f41c"
    hash = "sha256-BINp4dv+7y8SZCdDQ1T/5kT4lsYqbkZKrA3QWaVSeAE="
  [mod."google.golang.org/grpc"]
    version = "v1.51.0"
    hash = "sha256-RzH5DU13D/ulxxOouIKpdNt8eHdff7mrEnB+JUupbLU="
  [mod."google.golang.org/protobuf"]
    version = "v1.28.1"
    hash = "sha256-sTJYgvlv5is7vHNxcuigF2lNASp0QonhUgnrguhfHSU="
